export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const FINISH_INITIALIZE_ACCOUNT = 'FINISH_INITIALIZE_ACCOUNT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

// export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
// export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';

export const CREATE_TRAINING = 'CREATE_TRAINING';
export const DELETE_TRAINING = 'DELETE_TRAINING';

export const GET_TRAININGS = 'GET_TRAININGS';
export const GET_TRAINING = 'GET_TRAINING';
export const TRAINING_ERROR = 'TRAINING_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

